# Generated by Django 2.0.2 on 2018-07-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_auto_20180609_2212'),
        ('gameplay', '0007_auto_20180611_1412'),
    ]

    operations = [
    ]
